title:              Efe Can Kara
email:              efecan_kara@proton.me
description:        add, commit, push, repeat.
author:             Efe Can Kara
baseurl:            ""
url:                "https://efecankara.xyz"

# Social Profiles
twitter_username:   karsterrx
github_username:    KARSTERR
instagram_username: karsterr.dev
linkedin_username:  karsterr

# Add your google-analytics ID here to activate google analytics
google_analytics:   469776529 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
