### Site Settings ###
title               : Efe Can Kara
description         : C++ Dev | IoT Tinkerer | Data Analyst
baseurl             : ""            # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
url                 : https://efecankara.xyz/
repository          : KARSTERR/efecankara.xyz      # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : yousinix/portfolYOU
open_new_tab        : false                    # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**                           # For Documentation Only


### Author Info ###
author:
  name              : Efe Can Kara
  image             : pp.jpeg
  email             : efecan_kara@proton.me
  github            : KARSTERR
  gitlab            : KARSTERR
  linkedin          : # TO-DO get linkedin id
  stackoverflow     : # TO-DO get stackoverflow id
  youtube           : # TO-DO get youtube id


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:                                             # For Documentation Only
    output: true                                        # For Documentation Only


### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id
# TO-DO set google analytics

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:                                              # For Documentation Only
      path: ""                                          # For Documentation Only
      type: "elements"                                  # For Documentation Only
    values:                                             # For Documentation Only
      layout: "element"                                 # For Documentation Only
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
